const soma = require("./soma")
const subtracao = require("./subtracao")
const multiplicacao = require("./multiplicacao")
const divisao = require("./divisao")
console.log(soma(6, 2))
console.log(subtracao(6, 2))
console.log(multiplicacao(6, 2))
console.log(divisao(6, 2))